### ISSUE TITLE
Issue with iOS8

### ISSUE THREAD

**Issue by xena68** [HcDevel/Siri-API#19]
Upgraded my phone to iOS8 and now receive the following message in Safari:

"there was a problem communicating with the secure web proxy server (HTTPS)"

Used another phone (iOS7) in the house and it works fine, so squid and Siri-API seem to be running correctly.

Any ideas?

**Comment by HcDevel** [comment]
I just published a new, iOS8 compatible version here: https://github.com/HcDevel/SiriAPI8. It now uses iCloud notes instead of intercepting google requests and the installation became much easier. If you have any questions or problems, please create an issue in the new repo
