### ISSUE TITLE
afetr run Squid ...

### ISSUE THREAD

**Issue by quiquoi** [HcDevel/Siri-API#24]
hello,
after install Squid, it don't run : 

cm@cm-E1210:~$ /usr/local/squid/sbin/squid -NCd9
2014/11/05 13:41:51| SECURITY NOTICE: auto-converting deprecated "ssl_bump allow <acl>" to "ssl_bump client-first <acl>" which is usually inferior to the newer server-first bumping mode. Update your ssl_bump rules.
2014/11/05 13:41:51| WARNING: auto-converting deprecated "ssl_bump deny <acl>" to "ssl_bump none <acl>". Update your ssl_bump rules.
WARNING: Cannot write log file: /usr/local/squid/var/logs/cache.log
/usr/local/squid/var/logs/cache.log: Permission denied
         messages will be sent to 'stderr'.
2014/11/05 13:41:51| SECURITY NOTICE: auto-converting deprecated implicit "ssl_bump allow all" to "ssl_bump client-first all" which is usually inferior to the newer server-first bumping mode. New ssl_bump configurations must not use implicit rules. Update your ssl_bump rules.
2014/11/05 13:41:51| SECURITY NOTICE: auto-converting deprecated "ssl_bump allow <acl>" to "ssl_bump client-first <acl>" which is usually inferior to the newer server-first bumping mode. Update your ssl_bump rules.
2014/11/05 13:41:51| Current Directory is /home/cm
WARNING: Cannot write log file: /usr/local/squid/var/logs/cache.log
/usr/local/squid/var/logs/cache.log: Permission denied
         messages will be sent to 'stderr'.
2014/11/05 13:41:51| WARNING: Closing open FD    2
2014/11/05 13:41:51| Starting Squid Cache version 3.4.4 for i686-pc-linux-gnu...
2014/11/05 13:41:51| Process ID 4580
2014/11/05 13:41:51| Process Roles: master worker
2014/11/05 13:41:51| With 1024 file descriptors available
2014/11/05 13:41:51| Initializing IP Cache...
2014/11/05 13:41:51| DNS Socket created at [::], FD 4
2014/11/05 13:41:51| DNS Socket created at 0.0.0.0, FD 5
2014/11/05 13:41:51| Adding nameserver 127.0.0.1 from /etc/resolv.conf
2014/11/05 13:41:51| helperOpenServers: Starting 5/32 'ssl_crtd' processes
2014/11/05 13:41:51| WARNING: no_suid: setuid(0): (1) Operation not permitted
2014/11/05 13:41:51| WARNING: no_suid: setuid(0): (1) Operation not permitted
2014/11/05 13:41:51| WARNING: no_suid: setuid(0): (1) Operation not permitted
2014/11/05 13:41:51| WARNING: no_suid: setuid(0): (1) Operation not permitted
2014/11/05 13:41:51| WARNING: no_suid: setuid(0): (1) Operation not permitted
2014/11/05 13:41:51| Logfile: opening log daemon:/usr/local/squid/var/logs/access.log
2014/11/05 13:41:51| Logfile Daemon: opening log /usr/local/squid/var/logs/access.log
2014/11/05 13:41:51| WARNING: no_suid: setuid(0): (1) Operation not permitted
fopen: Permission denied
2014/11/05 13:41:51| Store logging disabled
2014/11/05 13:41:51| Swap maxSize 0 + 262144 KB, estimated 20164 objects
2014/11/05 13:41:51| Target number of buckets: 1008
2014/11/05 13:41:51| Using 8192 Store buckets
2014/11/05 13:41:51| Max Mem  size: 262144 KB
2014/11/05 13:41:51| Max Swap size: 0 KB
2014/11/05 13:41:51| Using Least Load store dir selection
2014/11/05 13:41:51| Current Directory is /home/cm
2014/11/05 13:41:51| Finished loading MIME types and icons.
2014/11/05 13:41:51| commBind: Cannot bind socket FD 18 to [::]:3128: (98) Address already in use
2014/11/05 13:41:51| HTCP Disabled.
2014/11/05 13:41:51| /usr/local/squid/var/run/squid.pid: (13) Permission denied
2014/11/05 13:41:51| Closing HTTP port [::]:3128
FATAL: Could not write pid file
Squid Cache (Version 3.4.4): Terminated abnormally.
CPU Usage: 0.144 seconds = 0.116 user + 0.028 sys
Maximum Resident Size: 39968 KB
Page faults with physical i/o: 0
Memory usage for squid via mallinfo():
	total space in arena:    4228 KB
	Ordinary blocks:         4170 KB      3 blks
	Small blocks:               0 KB      1 blks
	Holding blocks:           580 KB      2 blks
	Free Small blocks:          0 KB
	Free Ordinary blocks:      57 KB
	Total in use:            4750 KB 112%
	Total free:                57 KB 1%
Abandon (core dumped)

how resolve it and run squid ? 

thank you

**Comment by HcDevel** [comment]
no reply - closed
