### ISSUE TITLE
Html respond auto close

### ISSUE THREAD

**Issue by todely** [HcDevel/Siri-API#26]
Hi,

Does is possible to modify document.py to add fonction for closing html answer page and don't have to much tab open in safari after lot of request ?

Thanks !

**Comment by RobinMeis** [comment]
I tried it but it seems that Apple blocks an automatic close of the tab

**Comment by todely** [comment]
Argh...so bad... Just to know, if there was no apple block on this, how did you code automatic close of a tab ?

And thanks for your work !

**Comment by RobinMeis** [comment]
I tried it a few months ago, so I don't have any code right now. I think
Apple allows closing a tab only based on a user interaction. It's the
same with playing audio or video files which can't be automatically started.

**Comment by todely** [comment]
possible to add a button  to close tab ?

**Comment by RobinMeis** [comment]
This should be possible but I'm not able to test it as I don't use this old version anymore since I updated to iOS8
